apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aoc-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi # 10Mi should be plenty
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aoc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aoc-deployment
  template:
    metadata:
      labels:
        app: aoc-deployment
    spec:
      containers:
      - name: aoc-deployment
        image: ghcr.io/dustin-ward/advent-of-code-discord:latest
        env:
          - name: AOC_BOT_TOKEN
            value: "[YOUR TOKEN THERE]" # https://discord.com/developers/applications
          - name: "DATA_DIR"
            value: "/data/"

        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        volumeMounts:
          - name: aoc-volume 
            mountPath: /data/
      volumes:
      - name: aoc-volume
        persistentVolumeClaim:
          claimName: aoc-pvc
